import type { Metadata } from "next";
import { listSignals } from "@/features/signals/queries";
export const metadata: Metadata = { title: "Signals" };
export const dynamic = "force-dynamic";
export default async function SignalsPage({ searchParams }: { searchParams: Promise<{ retailer?: string; scope?: string }> }) {
  const filters = await searchParams;
  const { signals, sourceState } = await listSignals(filters);
  return <div className="page"><div className="page-heading"><h1>Signals</h1><p>Chronological public crowd evidence. Reports can be wrong, delayed, or incomplete.</p></div><form className="signal-filters" aria-label="Signal filters"><label>Retailer<select name="retailer" defaultValue={filters.retailer ?? ""}><option value="">All retailers</option><option value="ross">Ross</option><option value="target">Target</option><option value="walmart">Walmart</option><option value="meijer">Meijer</option></select></label><label>Location<select name="scope" defaultValue={filters.scope ?? ""}><option value="">All scopes</option><option value="LOCAL">Local / named store</option><option value="REGIONAL">Regional</option><option value="NATIONAL">National</option><option value="UNKNOWN">Unknown</option></select></label><button type="submit">Apply filters</button></form>{sourceState === "fixture" ? <aside className="partial-banner"><strong>Fixture demo.</strong> Synthetic Reddit/Ross records exercise sanitization, scopes, deduplication, and ranking without live access.</aside> : sourceState === "cached" || sourceState === "unavailable" ? <aside className="partial-banner"><strong>Reddit unavailable.</strong> {sourceState === "cached" ? "Showing cached signals with their original timestamps." : "No cached signals are present."} This is not an inventory conclusion.</aside> : null}{signals.length ? <div className="signal-list">{signals.map((signal) => <article className="signal-card" key={signal.id}><div className="signal-meta"><span>{signal.retailer}</span><span className={`scope-badge scope-${signal.locationScope.toLowerCase()}`}>{signal.locationLabel}</span>{signal.reviewRequired ? <span className="review-badge">Review</span> : null}</div><h2>{signal.title}</h2>{signal.excerpt ? <p>{signal.excerpt}</p> : null}<div className="signal-footer"><span>{signal.evidenceLabel}</span><time dateTime={signal.postedAt}>{new Date(signal.postedAt).toLocaleString("en-US", { timeZone: "America/Indiana/Indianapolis" })}</time><a href={signal.permalink} target="_blank" rel="noreferrer noopener">Open public post <span className="sr-only">(opens in a new tab)</span>↗</a></div></article>)}</div> : <section className="empty-state"><h2>No signals match</h2><p>Try broader filters. A missing report does not mean a product is unavailable.</p></section>}</div>;
}
