import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getProduct } from "@/features/catalog/queries";
import { ClassificationActions } from "@/components/products/classification-actions";
import { ProductThumbnail } from "@/components/products/product-thumbnail";
import { availabilityLabel, formatCurrency, formatFreshness } from "@/features/presentation/format";
import { listSignals } from "@/features/signals/queries";
import { parseEnv } from "@/config/env";

export const metadata: Metadata = { title: "Product detail" };
export default async function ProductPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const product = await getProduct(id); if (!product) notFound();
  const env = parseEnv();
  const readOnlyPreview = env.NODE_ENV === "production" && env.SHELF_RADAR_DATA_MODE === "fixture";
  const presentationNow = env.SHELF_RADAR_DATA_MODE === "fixture" ? new Date("2026-07-18T21:00:00.000Z") : new Date();
  const observations = product.listings.flatMap((listing) => listing.availability.map((observation) => ({ ...observation, listing })));
  const relatedSignals = (await listSignals({ productId: product.id, retailer: "ross" })).signals.slice(0, 3);
  const listingRetailers = new Set(product.listings.map((listing) => listing.retailerKey));
  const fieldShortcuts = [
    ...product.listings.flatMap((listing) => listing.fieldStores.map((store) => ({ key: `${listing.id}:${store.id}`, retailer: listing.retailer, retailerKey: listing.retailerKey, listingId: listing.id, store }))),
    ...product.scoutStores.filter((store) => !listingRetailers.has(store.retailerKey)).map((store) => ({ key: `scout:${store.retailerKey}:${store.id}`, retailer: store.retailer, retailerKey: store.retailerKey, listingId: undefined, store }))
  ];
  return <div className="page detail-page"><Link href="/discover" className="back-link">← Back to Discover</Link><section className="detail-hero"><ProductThumbnail name={product.name} imageUrl={product.imageUrl} priority /><div><h1>{product.name}</h1><p>{product.brand} · {product.line}</p></div></section><ClassificationActions productId={product.id} initialState={product.state} readOnly={readOnlyPreview} />
    <section className="detail-section"><h2>Identifiers</h2><dl className="identifier-grid">{product.identifiers.map((identifier) => <div key={`${identifier.kind}:${identifier.value}`}><dt>{identifier.kind}</dt><dd>{identifier.value}</dd></div>)}</dl></section>
    <section className="detail-section"><h2>Retailer listings</h2><div className="listing-list">{product.listings.map((listing) => <div className="listing-row" key={listing.id}><div><strong>{listing.retailer}</strong><p>{formatCurrency(listing.priceMinor)} · {listing.status.toLowerCase().replaceAll("_", " ")} · {listing.sourceState === "fixture-only" ? "fixture-only" : listing.sourceState === "pending-sanctioned-access" ? "cached; pending sanctioned access" : listing.sourceState === "unavailable" ? "cached; source unavailable" : "live"}</p></div><div className="listing-actions">{listing.actionLinks.map((link) => <a key={`${link.kind}:${link.url}`} href={link.url} target="_blank" rel="noreferrer noopener">{link.label} <span className="sr-only">(opens in a new tab)</span>↗</a>)}</div></div>)}</div></section>
    <section className="detail-section"><h2>Availability observations</h2>{observations.length ? <div className="observation-list">{observations.map((item) => <div className="observation" key={`${item.listing.id}:${item.storeName}:${item.observedAt}`}><span className={item.sourceAvailable && item.listing.sourceState !== "unavailable" ? "fresh-dot" : "neutral-dot"} aria-hidden="true" /><div><strong>{item.sourceKind === "owner_manual_field_check" ? item.rawLabel ?? "Owner field check" : availabilityLabel(item.status)}</strong><p>{item.storeName} · {item.listing.retailer}{item.sourceKind === "owner_manual_field_check" ? " · your field check" : item.listing.sourceState === "unavailable" ? " · cached while source unavailable" : ""}</p></div><time dateTime={item.observedAt}>{formatFreshness(item.observedAt, presentationNow)}</time></div>)}</div> : <p>No availability observations recorded.</p>}<aside className="truth-note"><strong>Retailer signals are not proof of shelf inventory.</strong><span> Items can sell out, be removed, or never reach the sales floor.</span></aside></section>
    <section className="detail-section"><h2>Field check shortcuts</h2><div className="field-shortcuts">{fieldShortcuts.map((shortcut) => <form className="field-shortcut" action="/api/hunts/field-check" method="post" key={shortcut.key}><input type="hidden" name="next" value={`/products/${product.id}`} /><input type="hidden" name="productId" value={product.id} /><input type="hidden" name="listingId" value={shortcut.listingId ?? ""} /><input type="hidden" name="retailerKey" value={shortcut.retailerKey} /><input type="hidden" name="storeId" value={shortcut.store.id} /><input type="hidden" name="mutationId" value={crypto.randomUUID()} /><div><strong>{shortcut.store.name}</strong><p>{shortcut.retailer} · {shortcut.store.city}, {shortcut.store.region}</p></div><div className="field-check-buttons"><button type="submit" name="status" value="OUT_OF_STOCK" disabled={readOnlyPreview}>None</button><button type="submit" name="status" value="UNKNOWN" disabled={readOnlyPreview}>Unsure</button><button type="submit" name="status" value="LIMITED" disabled={readOnlyPreview}>Limited</button><button type="submit" name="status" value="IN_STOCK" disabled={readOnlyPreview}>Saw it</button></div></form>)}</div>{fieldShortcuts.length ? <p className="field-note">These are your observations, not retailer inventory claims. Scout shortcuts create manual retailer check records when needed.</p> : <p>No named physical stores are configured for this product’s retailers yet.</p>}</section>
    {relatedSignals.length ? <section className="detail-section"><h2>Related public sightings</h2>{relatedSignals.map((signal) => <article className="related-signal" key={signal.id}><div className="signal-meta"><span className={`scope-badge scope-${signal.locationScope.toLowerCase()}`}>{signal.locationLabel}</span>{signal.reviewRequired ? <span className="review-badge">Product match needs review</span> : null}</div><h3>{signal.title}</h3><p>{signal.reviewRequired ? "Crowd evidence with an unconfirmed product match; not a retailer inventory observation." : "Crowd evidence only; not a retailer inventory observation."}</p><a href={signal.permalink} target="_blank" rel="noreferrer noopener">Open public post <span className="sr-only">(opens in a new tab)</span>↗</a></article>)}</section> : null}
    <section className="detail-section"><h2>Product details</h2><dl className="details-list"><div><dt>Brand / line</dt><dd>{product.brand} / {product.line}</dd></div><div><dt>Type</dt><dd>{product.productType}</dd></div><div><dt>Matching</dt><dd>{product.matchingSummary}</dd></div></dl></section></div>;
}
